-- Migration: Create OTP Program Tables
-- Created: 2026-01-01
-- Description: Tables for storing HSE OTP master programs and monthly progress

-- Table for master programs (OTP, Matrix, etc.)
CREATE TABLE public.master_programs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    program_type TEXT NOT NULL DEFAULT 'otp', -- 'otp', 'matrix'
    region TEXT NOT NULL DEFAULT 'indonesia', -- 'indonesia', 'asia'
    base TEXT NOT NULL DEFAULT 'all', -- 'narogong', 'duri', 'balikpapan', 'all'
    plan_type TEXT, -- 'yearly', 'monthly', 'quarterly', 'semester'
    due_date DATE,
    category TEXT,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table for monthly progress data linked to programs
CREATE TABLE public.program_progress (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    program_id BIGINT REFERENCES public.master_programs(id) ON DELETE CASCADE,
    month TEXT NOT NULL, -- 'jan', 'feb', 'mar', etc.
    year INTEGER NOT NULL DEFAULT 2026,
    plan_value INTEGER DEFAULT 0,
    actual_value INTEGER DEFAULT 0,
    wpts_id TEXT,
    plan_date DATE,
    impl_date DATE,
    pic_name TEXT,
    pic_email TEXT,
    status TEXT DEFAULT 'pending', -- 'pending', 'completed', 'overdue'
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for better query performance
CREATE INDEX idx_programs_type ON public.master_programs(program_type);
CREATE INDEX idx_programs_region ON public.master_programs(region);
CREATE INDEX idx_programs_base ON public.master_programs(base);
CREATE INDEX idx_progress_program_id ON public.program_progress(program_id);
CREATE INDEX idx_progress_month_year ON public.program_progress(month, year);

-- Enable RLS (Row Level Security)
ALTER TABLE public.master_programs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.program_progress ENABLE ROW LEVEL SECURITY;

-- Public Access Policies (Open for now, will lock down later with auth)
CREATE POLICY "Allow public read programs" ON public.master_programs FOR SELECT USING (true);
CREATE POLICY "Allow public all programs" ON public.master_programs FOR ALL USING (true);
CREATE POLICY "Allow public read progress" ON public.program_progress FOR SELECT USING (true);
CREATE POLICY "Allow public all progress" ON public.program_progress FOR ALL USING (true);

-- Comments for documentation
COMMENT ON TABLE public.master_programs IS 'Master table for HSE OTP and Matrix programs';
COMMENT ON TABLE public.program_progress IS 'Monthly progress tracking for each program';
COMMENT ON COLUMN public.master_programs.plan_type IS 'Frequency: yearly, monthly, quarterly, semester';
COMMENT ON COLUMN public.program_progress.plan_value IS 'Target value for the month';
COMMENT ON COLUMN public.program_progress.actual_value IS 'Actual achieved value for the month';
