-- Migration: Create KPI Tables
-- Created: 2026-01-01
-- Description: Tables for storing HSE KPI yearly summary and individual metrics

-- Table for storing yearly summary (Man Hours)
CREATE TABLE public.hse_kpi_years (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year INTEGER NOT NULL UNIQUE,
    man_hours BIGINT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table for individual metrics (TRIR, PVIR, etc.) linked to a year
CREATE TABLE public.hse_kpi_metrics (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    year_id BIGINT REFERENCES public.hse_kpi_years(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    target NUMERIC DEFAULT 0,
    result NUMERIC DEFAULT 0,
    icon TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for better query performance
CREATE INDEX idx_kpi_years_year ON public.hse_kpi_years(year);
CREATE INDEX idx_kpi_metrics_year_id ON public.hse_kpi_metrics(year_id);

-- Enable RLS (Row Level Security)
ALTER TABLE public.hse_kpi_years ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hse_kpi_metrics ENABLE ROW LEVEL SECURITY;

-- Public Access Policies (Open for now, will lock down later)
CREATE POLICY "Allow public read years" ON public.hse_kpi_years FOR SELECT USING (true);
CREATE POLICY "Allow public insert/update years" ON public.hse_kpi_years FOR ALL USING (true);
CREATE POLICY "Allow public read metrics" ON public.hse_kpi_metrics FOR SELECT USING (true);
CREATE POLICY "Allow public insert/update metrics" ON public.hse_kpi_metrics FOR ALL USING (true);

-- Insert default years
INSERT INTO public.hse_kpi_years (year, man_hours) VALUES 
    (2024, 0),
    (2025, 0),
    (2026, 0);

-- Comments for documentation
COMMENT ON TABLE public.hse_kpi_years IS 'Stores yearly KPI summary including man hours';
COMMENT ON TABLE public.hse_kpi_metrics IS 'Stores individual KPI metrics like TRIR, PVIR, etc.';
COMMENT ON COLUMN public.hse_kpi_metrics.target IS 'Target value for the metric';
COMMENT ON COLUMN public.hse_kpi_metrics.result IS 'Actual result/achievement for the metric';
